version: '3.8'

services:

  lb:
    build: .
    container_name: load-balancer

    ports:
      - "8080:8080"

    environment:
      SERVER_PORT: 8080
      APP_ROLE: loadbalancer

      # host:port:weight
      BACKEND_INSTANCES: app1:8080:1,app2:8080:3,app3:8080:2

    depends_on:
      - app1
      - app2
      - app3

    networks:
      - ecommerce-net

  app1:
    build: .
    environment:
      SERVER_PORT: 8080
      APP_ROLE: worker
      APP_NAME: app2
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - ecommerce-net

  app2:
    build: .
    environment:
      SERVER_PORT: 8080
      APP_ROLE: worker
      APP_NAME: app2
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - ecommerce-net

  app3:
    build: .
    environment:
      SERVER_PORT: 8080
      APP_ROLE: worker
      APP_NAME: app2
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - ecommerce-net

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - ecommerce-net

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - ecommerce-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge