version: '3.8'

services:

  lb:
    build: .
    cpus: "1.0"
    mem_limit: 512m

    ports:
      - "${LB_PORT:-8080}:8080"

    environment:
      SERVER_PORT: 8080
      APP_ROLE: loadbalancer
      SPRING_BATCH_JOB_ENABLED: false
      JAVA_TOOL_OPTIONS: "-XX:ActiveProcessorCount=2 -XX:CICompilerCount=2 -XX:MaxRAMPercentage=70 -Djava.security.egd=file:/dev/urandom"

      # host:port:weight
      BACKEND_INSTANCES: app1:8080:1,app2:8080:3,app3:8080:2

    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      app1:
        condition: service_started
      app2:
        condition: service_started
      app3:
        condition: service_started

    networks:
      - ecommerce-net

  app1:
    build: .
    cpus: "1.0"
    mem_limit: 512m
    ports:
      - "${APP1_PORT:-8081}:8080"
    environment:
      - SERVER_PORT=8080
      - APP_ROLE=worker
      - APP_NAME=app1
      - "JAVA_TOOL_OPTIONS=-XX:ActiveProcessorCount=2 -XX:CICompilerCount=2 -XX:MaxRAMPercentage=70 -Djava.security.egd=file:/dev/urandom"
      - BATCH_JOB_ENABLED=false
      - SPRING_BATCH_JOB_ENABLED=false
      - APP_SEED_ENABLED=true
      - APP_SEED_USERS=500
      - APP_SEED_PRODUCTS=500
      - APP_SEED_ORDERS=1000
      - APP_SEED_SALES=2000
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - ecommerce-net

  app2:
    build: .
    cpus: "1.0"
    mem_limit: 512m
    ports:
      - "${APP2_PORT:-8082}:8080"
    environment:
      - SERVER_PORT=8080
      - APP_ROLE=worker
      - APP_NAME=app2
      - "JAVA_TOOL_OPTIONS=-XX:ActiveProcessorCount=2 -XX:CICompilerCount=2 -XX:MaxRAMPercentage=70 -Djava.security.egd=file:/dev/urandom"
      - BATCH_JOB_ENABLED=false
      - SPRING_BATCH_JOB_ENABLED=false
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - ecommerce-net

  app3:
    build: .
    cpus: "1.0"
    mem_limit: 512m
    ports:
      - "${APP3_PORT:-8083}:8080"
    environment:
      - SERVER_PORT=8080
      - APP_ROLE=worker
      - APP_NAME=app3
      - "JAVA_TOOL_OPTIONS=-XX:ActiveProcessorCount=2 -XX:CICompilerCount=2 -XX:MaxRAMPercentage=70 -Djava.security.egd=file:/dev/urandom"
      - BATCH_JOB_ENABLED=false
      - SPRING_BATCH_JOB_ENABLED=false
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - ecommerce-net

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 10s
      retries: 12
      start_period: 90s
    networks:
      - ecommerce-net

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    networks:
      - ecommerce-net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "${RABBITMQ_AMQP_PORT:-5672}:5672"
      - "${RABBITMQ_MGMT_PORT:-15672}:15672"

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge

volumes:
  mysql_data:
  rabbitmq_data:
