spring.application.name=demo
server.port=${SERVER_PORT:8080}

# MySQL
spring.datasource.url=jdbc:mysql://mysql:3306/ecommerce?rewriteBatchedStatements=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Redis (Shared Sessions)
spring.cache.type=redis
spring.session.store-type=redis
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Load Balancer (Backend Servers: name:port:weight)
backend.instances=${BACKEND_INSTANCES:app1:8080:1,app2:8080:3,app3:8080:1}

# Virtual Threads
spring.threads.virtual.enabled=true

#Logging
logging.level.com.example.demo.aspect=INFO
logging.level.root=INFO
logging.level.com.example.demo=INFO

#Batch
spring.batch.jdbc.initialize-schema=always
spring.sql.init.mode=never
spring.batch.job.enabled=${BATCH_JOB_ENABLED:false}

# Database seed
app.seed.enabled=${APP_SEED_ENABLED:false}
app.seed.reset=${APP_SEED_RESET:false}
app.seed.users=${APP_SEED_USERS:1000}
app.seed.products=${APP_SEED_PRODUCTS:500}
app.seed.orders=${APP_SEED_ORDERS:5000}
app.seed.sales=${APP_SEED_SALES:20000}
app.seed.owner-app=${APP_SEED_OWNER_APP:app1}


# metrics endpoints
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.metrics.enabled=true